version: "3.5"

services:
  w9gw:
    build:
      context: .
    networks:
      - w9gw
    image: dievri/webhook-9p-gateway:latest
    volumes:
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  inferno:
    image: deivri/inferno-webhook:latest
    build:
      context: .
      dockerfile: Dockerfile.webhook_queue
    volumes:
      - ./files/inferno/profile:/usr/inferno-os/lib/sh/profile:ro
    networks:
      - w9gw
    environment: 
      EXPORT_PORT: 1917
      EXPORT_PATH: /
    entrypoint:
      - sh
      - -exc
      - |
        emu-g /dis/sh /lib/sh/profile / 1917
    

networks:
  w9gw:
    name: w9gw
    driver: bridge
