version: "3.5"

services:
  w9gw:
    build:
      context: .
    networks:
      - w9gw
    image: dievri/webhook-9p-gateway:latest
    environment:
      NINEP_HOST: inferno
      NINEP_PORT: 1917
    volumes:
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - "8080:80"

  inferno:
    image: deivri/inferno-webhook:latest
    build:
      context: .
      dockerfile: Dockerfile.webhook_queue
    volumes:
      - ./files/inferno/profile:/usr/inferno-os/lib/sh/profile:ro
    networks:
      - w9gw
    environment: 
      EXPORT_PORT: 1917
      EXPORT_PATH: /
    entrypoint:
      - sh
      - -exc
      - |
        emu-g /dis/sh /lib/sh/profile
    

networks:
  w9gw:
    name: w9gw
    driver: bridge
